version: '3'

services:

  james:
    image: apache/james:memory-latest
    container_name: james
    hostname: james.local
    volumes:
      - $PWD/target/james-server-rate-limiter-3.8.0-SNAPSHOT-jar-with-dependencies.jar:/root/extensions-jars/james-server-rate-limiter.jar
      - $PWD/extensions.properties:/root/conf/extensions.properties
      - $PWD/mailetcontainer.xml:/root/conf/mailetcontainer.xml
