version: '3'

services:

  james:
    depends_on:
      - elasticsearch
    image: apache/james:memory-latest
    container_name: james
    hostname: james.local
    volumes:
      - ./conf/keystore:/root/conf/keystore
      - ./target/apache-james-elasticsearch-3.8.0-SNAPSHOT-jar-with-dependencies.jar:/root/extensions-jars/apache-james-elasticsearch-3.8.0-SNAPSHOT-jar-with-dependencies.jar
      - ./conf/extensions.properties:/root/conf/extensions.properties
      - ./conf/elasticsearch.properties:/root/conf/elasticsearch.properties

  elasticsearch:
    image: elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
